version: '3.7'

services:
  flask_app:
    build: .
    environment:
      - DATABASE_URL=postgres://user:pass@db/user
    volumes:
      - .:/opt/source-code
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes: 
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=user