version: '3'
services:
  flask_app:
    build: ./flask_app
    restart: always
    environment:
      - DATABASE_URL=postgres://user:pass@db/user
    volumes:
      - ./flask_app:/opt/source-code
    expose:
      - 5000
    depends_on:
      - db
    command: gunicorn -w 1 -b 0.0.0.0:5000 app:app

  db:
    image: postgres:12-alpine
    volumes: 
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=user

  nginx:
    build: ./nginx
    volumes:
      - ./flask_app/opt/source-code
    ports:
       - 1337:80
    depends_on:
       - flask_app